# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Update team projects
on:
  issues:
    types: [assigned, unassigned, labeled, unlabeled]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
    
      - name: Simple thing
        run: |
          echo 'Hello from bash'
          echo $PWD
          ls -al
          python -m actions.action
