name: Update team projects
on:
  issues:
    types: [assigned, labeled, unlabeled]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
    
      - name: Simple thing
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 -m actions.update_teams
