# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Update team projects
on:
  issues:
    types: [assigned, unassigned, labeled, unlabeled]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
    
      - name: Simple thing
        env:
          GITHUB_CONTEXT: "${{ toJson(github) }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          echo 'Hello from bash'
          echo $PWD
          echo "$GITHUB_CONTEXT"
          echo "$GITHUB_TOKEN"
          python3 -m actions.action
